ERROR_CODES = {
    # Group similar errors under the same code
    "CORE_TEMP": ("AA01", ["A", "BG", "BY"]),
    "COOLANT_FLOW": ("AB02", ["B", "BW"]),
    "CONTROL_ROD": ("AC03", ["C", "J", "AL", "BL"]),
    "RADIATION_LEAK": ("AD04", ["D", "CB", "AY", "BJ"]),
    "EMERGENCY_POWER": ("AE05", ["E"]),
    "SIGNAL_INTERFERENCE": ("AF06", ["F"]),
    "GENERATOR_OSC": ("AG07", ["G"]),
    "PRESSURE_SENSOR": ("AH08", ["H"]),
    "NEUTRON_FLUX": ("AI09", ["I"]),
    "CONTAINMENT_SEAL": ("AJ10", ["K", "AX"]),
    "SCRAM_OVERDUE": ("AK11", ["L"]),
    "RADIATION_MONITOR": ("AL12", ["M"]),
    "POWER_GRID": ("AM13", ["N", "O", "BI"]),
    "WATER_LEVEL": ("AN14", ["P"]),
    "VENTILATION_AIRFLOW": ("AO15", ["Q", "AS", "AV", "BN", "AG"]),
    "OPERATOR_CONSOLE": ("AP16", ["R"]),
    "FIRE_SUPPRESSION": ("AQ17", ["S"]),
    "HEAT_EXCHANGER": ("AR18", ["T"]),
    "DATA_LOGGER": ("AS19", ["U", "BU"]),
    "SYSTEM_DIAGNOSTICS": ("AT20", ["V"]),
    "AIR_INTAKE": ("AU21", ["Y"]),
    "COOLANT_PUMP": ("AV22", ["AA", "BM", "CC"]),
    "THERMAL_SHIELD": ("AW23", ["AB", "BO"]),
    "AIRFLOW_REGULATOR": ("AX24", ["AC"]),
    "REACTOR_CORE": ("AY25", ["AD"]),
    "EXHAUST_SYSTEM": ("AZ26", ["AE"]),
    "TURBINE_SPEED": ("BA27", ["AF"]),
    "COOLANT_FILTER": ("BB28", ["AH"]),
    "RADIATION_SHIELD": ("BC29", ["AI"]),
    "HYDRAULIC_SYSTEM": ("BD30", ["AK"]),
    "VENTILATION_MOTOR": ("BE31", ["AM"]),
    "PRESSURE_VALVE": ("BF32", ["AN"]),
    "COOLANT_LEAK": ("BG33", ["AP", "BP"]),
    "SENSOR_ARRAY": ("BH34", ["AQ"]),
    "OVERPRESSURE_EVENT": ("BI35", ["AR", "BD"]),
    "BACKUP_SYSTEM": ("BJ36", ["AT"]),
    "THERMAL_RUNAWAY": ("BK37", ["AU"]),
    "CONTROL_PANEL": ("BL38", ["AW"]),
    "MAINTENANCE_LOG": ("BM39", ["AZ"]),
    "FUEL_ROD": ("BN40", ["BB"]),
    "COOLANT_TEMP": ("BO41", ["BC"]),
    "CORE_INSTABILITY": ("BP42", ["BS"]),
    "HEAT_SINK": ("BQ43", ["BQ"]),
    "LOG_SYSTEM": ("BR44", ["BU"]),
    "SENSOR_CALIB": ("BS45", ["BX"]),
    "SYSTEM_CLOCK": ("BT46", ["BF"]),
}

# Build a mapping from error letter to code
ERROR_LETTER_TO_CODE = {}
for code, (code_str, letters) in ERROR_CODES.items():
    for letter in letters:
        ERROR_LETTER_TO_CODE[letter] = code_str

ERRORS = [
    (letter, f"{msg} CODE: {ERROR_LETTER_TO_CODE.get(letter, 'UNKN00')}", data)
    for (letter, msg, data) in [
        ("A", "[WARN] CoreTempMonitor: Temperature Monitor readings are inaccurate - recalibration required.", {"inaccuracy": +10, "temperature": +2}),
        ("B", "[INFO] CoolantFlowRate: Detected 68% of nominal flow — check secondary pump performance.", {"temperature": +5, "pressure": +3, "airflow": -1, "fix_message": "RESTARTING"}),
        ("C", "[WARN] Primary control rod unresponsive.", {"temperature": +8, "pressure": +2, "fix_message": "CHECKING HYDRAULICS"}),
        ("D", "[WARN] Radiation leak detected!", {"temperature": +20, "pressure": +10, "airflow": -5, "fix_message": "INITIATING CONTAINMENT PROTOCOLS"}),
        ("E", "[WARN] Emergency power offline.", {"temperature": -20, "pressure": -5, "airflow": -3, "fix_message": "REBOOTING"}),
        ("F", "[INFO] Signal interference in command relay.", {"temperature": +2, "airflow": +1, "fix_message": "RECONNECTING"}),
        ("G", "[INFO] Backup generator oscillation abnormality.", {"temperature": +15, "airflow": -2, "fix_message": "RESTARTING"}),
        ("H", "[ERR] Core pressure sensor mismatch.", {"pressure": +8, "fix_message": "RECALIBRATING"}),
        ("I", "[INFO] NeutronFluxSensor: Flux trending upward — initiate damping procedures.", {"temperature": +15, "fix_message": "DAMPING"}),
        ("J", "[ERR] ControlRodArray: Rod #4 insertion delay (2.7s) — verify hydraulic response.", {"temperature": +5, "fix_message": "CHECKING HYDRAULICS"}),
        ("K", "[INFO] ContainmentSealChk: Slight pressure deviation in Sector A2 — inspect for micro-leaks.", {"pressure": +2, "airflow": -1, "fix_message": "CORRECTING"}),
        ("L", "[WARN] EmergencySCRAM: System test overdue by 96 hours — perform routine validation.", {"temperature": -10, "fix_message": "VERIFYING INTEGRITY"}),
        ("M", "[INFO] RadiationMonitor: Gamma levels in service tunnel approaching alert threshold.", {"temperature": +3, "airflow": -2, "fix_message": "MONITORING"}),
        ("N", "[ERR] PowerGridSync: Voltage fluctuation detected in Sector 3 — immediate attention required.", {"pressure": +5, "fix_message": "STABILIZING"}),
        ("O", "[INFO] PowerGridSync: Phase drift within acceptable range — monitor closely.", {"fix_message": "MONITORING"}),
        ("P", "[WARN] WaterLevelSensor: Primary coolant reservoir down 6.2% — consider top-off.", {"temperature": +4, "airflow": -1, "fix_message": "PUMPING COOLANT"}),
        ("Q", "[WARN] VentilationSystem: Airflow in Sector B1 reduced by 12% — inspect ducting for blockages.", {"temperature": +2, "airflow": -5, "fix_message": "CLEANING VENTILATION"}),
        ("R", "[ERR] OperatorConsole: Button lag detected on Terminal A-2 — recalibration recommended.", {"temperature": +1, "lag": +3, "fix_message": "RECALIBRATING"}),
        ("S", "[INFO] FireSuppressSys: Suppression agent reservoir at 28% — refill soon.", {"temperature": +5, "airflow": -2, "fix_message": "REFILLING"}),
        ("T", "[WARN] HeatExchanger: Differential temp 14°C above optimal — increase secondary loop flow.", {"temperature": +10, "airflow": -3}),
        ("U", "[INFO] DataLogger: Telemetry backlog detected — compress logs and resume transmission.", {"temperature": +2, "fix_message": "TRANSMITTING"}),
        ("V", "[INFO] SystemDiagnostics: Non-critical hardware fault in Sensor Node 14A — replace within 24h.", {"temperature": +3, "fix_message": "REPLACING SENSOR"}),
        ("Y", "[INFO] AirIntake: Dust buildup detected in intake filters — schedule cleaning.", {"airflow": -3, "temperature": +2, "fix_message": "CLEANING FILTERS"}),
        ("AA", "[WARN] CoolantPump: Backup pump vibration anomaly — inspect bearings.", {"temperature": +6, "pressure": +3, "fix_message": "REPAIRING PUMP"}),
        ("AB", "[INFO] ThermalShield: Minor wear detected in shielding layer — monitor for degradation.", {"temperature": +3, "fix_message": "INSPECTING SHIELD"}),
        ("AC", "[ERR] Airflow Regulator: Control valve stuck at 20% — immediate repair needed.", {"airflow": -10, "temperature": +5, "fix_message": "ADJUSTING VALVE"}),
        ("AD", "[WARN] ReactorCore: Micro-fissure detected in core lining — assess structural integrity.", {"temperature": +8, "pressure": +5, "fix_message": "SEALING FISSURE"}),
        ("AE", "[INFO] ExhaustSystem: Backpressure 8% above normal — check exhaust ports.", {"pressure": +3, "airflow": -2, "fix_message": "CLEARING EXHAUST"}),
        ("AF", "[ERR] TurbineSpeed: Turbine overspeed detected — reduce load immediately.", {"pressure": +6, "temperature": +4, "fix_message": "SLOWING TURBINE"}),
        ("AH", "[INFO] CoolantFilter: Clogging detected at 15% — replace filter soon.", {"temperature": +3, "pressure": +2, "fix_message": "REPLACING FILTER"}),
        ("AI", "[ERR] RadiationShield: Breach in secondary shield — initiate lockdown.", {"temperature": +10, "pressure": +5, "fix_message": "REINFORCING SHIELD"}),
        ("AK", "[INFO] HydraulicSystem: Fluid pressure 5% below optimal — check for leaks.", {"pressure": -3, "fix_message": "INSPECTING LINES"}),
        ("AL", "[ERR] CoreAlignment: Misalignment of fuel rods detected — realign urgently.", {"temperature": +12, "pressure": +6, "fix_message": "REALIGNING RODS"}),
        ("AM", "[WARN] VentilationMotor: Overheating in motor #2 — reduce load or cool.", {"airflow": -4, "temperature": +5, "fix_message": "COOLING MOTOR"}),
        ("AN", "[INFO] PressureValve: Minor sticking detected in valve #5 — lubricate or replace.", {"pressure": +3, "fix_message": "LUBRICATING VALVE"}),
        ("AP", "[WARN] CoolantLeak: Trace coolant detected in containment — locate source.", {"temperature": +5, "pressure": -2, "fix_message": "SEALING LEAK"}),
        ("AQ", "[INFO] SensorArray: Intermittent signal loss from Node 7B — check connections.", {"temperature": +2, "fix_message": "RECONNECTING"}),
        ("AR", "[ERR] OverpressureEvent: Pressure spike in core chamber — vent excess now.", {"pressure": +10, "temperature": +5, "fix_message": "VENTING PRESSURE"}),
        ("AS", "[WARN] AirflowImbalance: Uneven flow between Sectors A and B — balance dampers.", {"airflow": -5, "temperature": +3, "fix_message": "BALANCING DAMPERS"}),
        ("AT", "[INFO] BackupSystem: Redundant circuit test passed with minor latency — log for review.", {"fix_message": "LOGGING DATA"}),
        ("AU", "[ERR] ThermalRunaway: Early signs of runaway reaction — reduce heat input.", {"temperature": +20, "pressure": +8, "fix_message": "COOLING CORE"}),
        ("AV", "[WARN] AirflowTurbine: Ventilation turbine vibration anomaly — inspect blades.", {"airflow": -6, "temperature": +4, "fix_message": "INSPECTING TURBINE"}),
        ("AW", "[INFO] ControlPanel: Display flicker on Terminal B-1 — check power supply.", {"fix_message": "STABILIZING POWER"}),
        ("AX", "[ERR] ContainmentBreach: Minor breach in outer containment — seal and monitor.", {"pressure": +5, "airflow": -3, "fix_message": "SEALING BREACH"}),
        ("AY", "[WARN] RadiationSpike: Sudden gamma spike in Sector C3 — evacuate and assess.", {"temperature": +10, "airflow": -5, "fix_message": "MONITORING RADIATION"}),
        ("AZ", "[INFO] MaintenanceLog: Routine check overdue for pump array — schedule soon.", {"fix_message": "SCHEDULING"}),
        ("BB", "[WARN] FuelRod: Wear detected in fuel rod #7 — replace within 48h.", {"temperature": +6, "pressure": +3, "fix_message": "REPLACING ROD"}),
        ("BC", "[INFO] CoolantTemp: Secondary loop temp 5°C above nominal — monitor trend.", {"temperature": +3, "fix_message": "MONITORING"}),
        ("BD", "[ERR] PressureSurge: Uncontrolled surge in core — initiate emergency vent.", {"pressure": +12, "temperature": +5, "fix_message": "VENTING"}),
        ("BF", "[INFO] SystemClock: Time sync drift detected — resynchronize clocks.", {"fix_message": "SYNCHRONIZING"}),
        ("BG", "[ERR] CoreOverheat: Core temp critical at 950°C — activate emergency cooling.", {"temperature": +25, "pressure": +5, "fix_message": "COOLING CORE"}),
        ("BI", "[INFO] PowerSupply: Minor voltage dip in backup grid — check regulators.", {"pressure": +2, "fix_message": "STABILIZING"}),
        ("BJ", "[ERR] RadiationAlarm: High beta radiation in exhaust — isolate and scrub.", {"temperature": +5, "airflow": -5, "fix_message": "SCRUBBING EXHAUST"}),
        ("BL", "[INFO] ControlRod: Minor wear in rod #6 mechanism — inspect at next shutdown.", {"temperature": +3, "fix_message": "INSPECTING"}),
        ("BM", "[ERR] CoolantFailure: Primary coolant pump offline — switch to backup.", {"temperature": +15, "pressure": +5, "fix_message": "SWITCHING PUMPS"}),
        ("BN", "[WARN] AirflowSensor: Tertiary sensor offline — verify connections.", {"airflow": -5, "temperature": +2, "fix_message": "RECONNECTING"}),
        ("BO", "[INFO] ShieldIntegrity: Minor erosion in thermal shield — monitor closely.", {"temperature": +4, "fix_message": "MONITORING"}),
        ("BP", "[ERR] PressureLeak: Rapid pressure drop in Sector A3 — locate leak.", {"pressure": -10, "airflow": -3, "fix_message": "SEALING LEAK"}),
        ("BQ", "[WARN] HeatSink: Efficiency down 9% — clean or replace heat sink.", {"temperature": +6, "fix_message": "CLEANING"}),
        ("BS", "[ERR] CoreInstability: Flux instability detected — stabilize reaction.", {"temperature": +15, "pressure": +8, "fix_message": "STABILIZING"}),
        ("BU", "[INFO] LogSystem: Error log nearing capacity — archive old entries.", {"fix_message": "ARCHIVING"}),
        ("BW", "[WARN] CoolantPressure: Low pressure in coolant line — check for blockages.", {"temperature": +5, "pressure": -3, "fix_message": "CLEARING LINE"}),
        ("BX", "[INFO] SensorCalib: Temp sensor #9 slightly off — recalibrate soon.", {"temperature": +2, "fix_message": "RECALIBRATING"}),
        ("BY", "[ERR] OverheatAlert: Core temp at 980°C — emergency shutdown imminent.", {"temperature": +30, "pressure": +10, "fix_message": "COOLING CORE"}),
        ("CA", "[INFO] PowerRelay: Minor delay in relay switch — test circuit.", {"fix_message": "TESTING"}),
        ("CB", "[ERR] RadiationSurge: Critical alpha radiation spike — seal Sector H1.", {"temperature": +10, "airflow": -5, "fix_message": "SEALING SECTOR"}),
        ("CC", "[WARN] PumpVibration: Excessive vibration in coolant pump #3 — inspect now.", {"temperature": +5, "pressure": +3, "fix_message": "REPAIRING PUMP"}),
    ]
]